version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    macos:
      xcode: "12.3.0"
    # executor:
    #   name: node/default
    #   tag: 14.3.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Test
          command: npm test

workflows:
  node-tests:
    jobs:
      - test
